CREATE TABLE orders
(
    ID            BIGINT         NOT NULL AUTO_INCREMENT,
    CREATION_TIME TIMESTAMP      NOT NULL,
    QUANTITY      INTEGER        NOT NULL,
    TOTAL_PRICE   DECIMAL(19, 2) NOT NULL,
    ITEM_ID       BIGINT         NOT NULL,
    PRIMARY KEY (ID)
)
