INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('PHONES', 'Flagman smartphone, produced in 2021 by Apple inc.', 'iPhone 13', 1000, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('PHONES', 'Eternal classic, produced in 2013 by Apple inc.', 'iPhone 5s', 50, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('PHONES', 'New Samsung flagman, produced in 2022', 'Samsung Galaxy S22', 1000, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('EARPHONES', 'Best Apple earphones', 'AirPods 2', 100, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('EARPHONES', 'Newest Apple earphones', 'AirPods 3', 180, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('EARPHONES', 'Vacuum Apple earphones', 'AirPods Pro', 250, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('CHARGERS', 'Best charger from chinese company', 'Baseus M482', 20, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('CHARGERS', 'Standard Apple charger', 'Apple charger', 20, 5);

INSERT INTO ITEMS (CATEGORY, DESCRIPTION, MODEL, PRICE, QUANTITY)
VALUES ('CHARGERS', 'Standard Samsung charger', 'Samsung charger', 20, 5);